name: CI

on:
  - push

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generating project
        run: swift package generate-xcodeproj
      - name: Testing
        run: |
          xcodebuild clean test -project FunctionalTableData.xcodeproj -scheme FunctionalTableData-Package -destination "platform=iOS Simulator,OS=13.4.1,name=iPhone 8"
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer
